baseURL = "https://financial-controller-dalton-86085.netlify.com/"
DefaultContentLanguage = "fr"
title = "Planiselect"
theme = "planiselect"
description = " Nous sommes des spécialistes en installation de réseaux informatiques : câblage structurés catégorie 5, catégorie 5e, catégorie 6 et fibre optique."

# Pointing to this file
config = "config.toml"
contentdir = "content"
disableKinds = ["RSS", "sitemap"]
# Create an array of files you don't want hugo to build
ignoreFiles = []
# Enable Logging
log = false
preserveTaxonomyNames = true
pygmentsUseClasses = true
relativeURLs = true
languageCode = "en-us"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = false

#CUSTOM PARAMS
[params]
  ## Include google maps, with API Key
  googleapikey = ""
  ## This is used when the BaseURL does not need to modified (eg, in share links)
  siteaddress = "https://www.planiselect.com/"
  siteaddressno = "https://www.planiselect.com"
  ## FB share info
  fbpagename = ""
  fbappid = ""
  ## Business name in Schema.org
  schemabiz = "Planiselect"
  ## Google Tag Manager tracking ID
  gtmid = "GTM-KSHK8KW"

# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true

[permalinks]
  singles = "/:slug/"

# [Languages.fr]
# [Languages.fr.Taxonomies]
# category = "categories"
# createur = "createurs"
